matrix:
  include:
  - language: ruby
    name: Rubocop (rvm 2.6)
    rvm: 2.6
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: B6+BLwHmV2wbYuzCR/Jp6GbHTCO0hGVEibBKFusfVDua1MO+K+91Lecefnt/K0tMA4j2Z2KSm8noZTOgGfjqThTCDgwo27VA5HKkPu3rbFsTfssJP571IfdKdfLzfRyIEDWnUw+19pnubAERTC9WeFhE+nRhkCB18lGqb+mDt4YdoWpssn0rMGbIBvnpX18wi/Z3M9bqwL0dWsx2IvIgBnKsS+ASr4DGBkRjZG12kEnkoXuhkZsP9yDph1acjoZA7mL8SBmG6atrba+O2dksW17JO+21qE438vazfIrmVmxMzBQxNKRpXtuTbfY1Piotc2N6oyFSgA8oTuN4I4o/VxopWQcO7jRpyyULshuN+BuA6JVSWT7WN1suLLeiNGlTgOYBYXxNVISr+Vr1NJORxrchvhNpcXEFJ0LVrIQT/oiP5f/IJt7JO23Z3w1Vni4THkL6lxVXtt6nJfjsj04ahrNbx/FRVCPFOKzT1mBjNongoHkQCC5A3C6UJkdicA75LR6cNoF7poXDnpHiq15m/nlXVV2zACXuY+1NZ+WZpXoQnysAPqGLG6wPjQAL7bmVlng0plESaGQWACPwhulxkEfrbOx8v3PZQ1xv4dHR/BY4WSUb7wSaTS79zYBqQGNTcNU3ieUfXuE5EeVGsJrdgZRZypx7FTZCo9NWh6a1buw=
